
= papertrail Connector Release Notes
////
[<System_Name>: papertrail]
////
:keywords: papertrail


The papertrail connector facilitates connections between Mule integration and papertrail applications. The papertrail connector  provides operations to know the systems list,loging destinations list,loging information of a systems associated to a particular account etc.

*Guide:* <Connector_Guide_Link>
////
Points to the docs.mulesoft pages for documentation on the functional aspects of the connector. e.g.: link:/mule-user-guide/v/3.7/microsoft-sharepoint-2013-connector[Microsoft SharePoint 2013 Connector]
////

== Version 1.0 - 1 January 2016
////
<Connector_Version> : Describes the connector version, such as “V2013”, “V4.0”, “V4.0.1-HF2” or whatever used for release]
<Release_date> : The date on which the connector is released (not when the notes are written, mind you)
////
=== Contents

- Compatibility
- Features
- Fixed in this Release
- Known Issues
- Support Resources

=== Compatibility

[width="100%", cols=",", options="header"]
|===
|Software |Version
|Mule Runtime |3.7.0
|NewRelic |1.0
|===





=== Features

. Version 1.0 Supported Operations
The PaperTrail Connector 1.0 allows you to perform the following operations:

PaperTrail Connector Operations +
 
1. Get Systems List +
2. Get Users List +
3. Get System Information +
4. Get Account Usage +
5. Get Groups List +
6. Get Destinations List +
7. Get Destination Information +
8. Get Archive Information +
9.Get Filter Logs +

=== Fixed in this Release
Version 1.0 Fixed in this Release
There are no bug fixes in this release.


=== Known Issues

Version 1.0 Known Issues
There are no reported issues that are unresolved in this release.

=== Support Resources

- Learn how to link:/mule-user-guide/v/3.7/installing-connectors[Install Anypoint Connectors] using Anypoint Exchange.
- Access MuleSoft’s MuleForge link:http://forum.mulesoft.org/mulesoft[Forum] to pose questions and get help from Mule’s broad community of users.
- To access MuleSoft’s expert support team, link:http://www.mulesoft.com/mule-esb-subscription[subscribe] to Mule ESB Enterprise and log in to MuleSoft’s link:http://www.mulesoft.com/support-login[Customer Portal].

